-- 1. Vehicles Table
CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand TEXT NOT NULL,
    model TEXT NOT NULL,
    year INT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Sedan', 'SUV', 'Luxury', 'Hatchback', 'Electric')),
    daily_rate NUMERIC(10, 2) NOT NULL CHECK (daily_rate > 0),
    fuel_type TEXT NOT NULL,
    seating_capacity INT NOT NULL DEFAULT 5,
    status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'rented', 'maintenance')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Rentals / Bookings Table
CREATE TABLE rentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE RESTRICT,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_cost NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'booked' CHECK (status IN ('booked', 'active', 'completed', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT valid_date_range CHECK (end_date >= start_date)
);

-- 3. Indexes for the collision query and user lookups
CREATE INDEX idx_rentals_vehicle_dates ON rentals (vehicle_id, start_date, end_date);
CREATE INDEX idx_rentals_user ON rentals (user_id);

-- 4. BONUS: database-level double-booking guard (protects against race conditions
--    when two requests pass the application check at the same moment).
CREATE EXTENSION IF NOT EXISTS btree_gist;
ALTER TABLE rentals ADD CONSTRAINT no_overlapping_rentals
    EXCLUDE USING gist (
        vehicle_id WITH =,
        daterange(start_date, end_date, '[]') WITH &&
    ) WHERE (status IN ('booked', 'active'));

-- 5. Sample data (3 vehicles)
INSERT INTO vehicles (brand, model, year, category, daily_rate, fuel_type, seating_capacity) VALUES
('Tesla',  'Model 3', 2024, 'Electric', 4500, 'EV',     5),
('Toyota', 'Fortuner', 2023, 'SUV',     5200, 'Diesel', 7),
('Honda',  'City',     2022, 'Sedan',   2500, 'Petrol', 5);
